name: proteingraph-dev
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- jupyter
- jupyterlab
- networkx
- pandas
- pytest
- numpy
- scipy
- scikit-learn
- bumpversion
- pytest
